### ISSUE TITLE
May I ask if you have solved this problem? I would like to ask for your advice.

### ISSUE THREAD

**Issue by ZB-BB** [ygswlgldmy/Pic_selecter#1]
There are 50 listed files in folder: Testset_50/
Performing prediction on 80 slices.
Performing inference on images:   0%|                                                               | 0/50 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/yolov11/tools/SAHI_predict.py", line 4, in <module>
    predict(
  File "anaconda3/envs/yolov11/lib/python3.10/site-packages/sahi/predict.py", line 559, in predict
    prediction_result = get_sliced_prediction(
  File "anaconda3/envs/yolov11/lib/python3.10/site-packages/sahi/predict.py", line 283, in get_sliced_prediction
    object_prediction_list = postprocess(object_prediction_list)
  File "anaconda3/envs/yolov11/lib/python3.10/site-packages/sahi/postprocess/combine.py", line 555, in __call__
    object_prediction_list[keep_ind] = merge_object_prediction_pair(
  File "anaconda3/envs/yolov11/lib/python3.10/site-packages/sahi/postprocess/utils.py", line 220, in merge_object_prediction_pair
    return ObjectPrediction(
  File "anaconda3/envs/yolov11/lib/python3.10/site-packages/sahi/prediction.py", line 79, in __init__
    super().__init__(
  File "anaconda3/envs/yolov11/lib/python3.10/site-packages/sahi/annotation.py", line 526, in __init__
    raise ValueError("Invalid segmentation mask.")
ValueError: Invalid segmentation mask.

**Comment by ZB-BB** [comment]
Traceback (most recent call last):

  File "D:\KSSB\ultralytics\sahi测试.py", line 27, in <module>
    result = get_sliced_prediction(

  File "D:\Anaconda\lib\site-packages\sahi\predict.py", line 283, in get_sliced_prediction
    object_prediction_list = postprocess(object_prediction_list)

  File "D:\Anaconda\lib\site-packages\sahi\postprocess\combine.py", line 555, in __call__
    object_prediction_list[keep_ind] = merge_object_prediction_pair(

  File "D:\Anaconda\lib\site-packages\sahi\postprocess\utils.py", line 220, in merge_object_prediction_pair
    return ObjectPrediction(

  File "D:\Anaconda\lib\site-packages\sahi\prediction.py", line 79, in __init__
    super().__init__(

  File "D:\Anaconda\lib\site-packages\sahi\annotation.py", line 525, in __init__
    raise ValueError("Invalid segmentation mask.")

ValueError: Invalid segmentation mask.


Have you solved it? How did you solve it?

**Comment by ygswlgldmy** [comment]
> Traceback (most recent call last):
> 
> File "D:\KSSB\ultralytics\sahi测试.py", line 27, in result = get_sliced_prediction(
> 
> File "D:\Anaconda\lib\site-packages\sahi\predict.py", line 283, in get_sliced_prediction object_prediction_list = postprocess(object_prediction_list)
> 
> File "D:\Anaconda\lib\site-packages\sahi\postprocess\combine.py", line 555, in **call** object_prediction_list[keep_ind] = merge_object_prediction_pair(
> 
> File "D:\Anaconda\lib\site-packages\sahi\postprocess\utils.py", line 220, in merge_object_prediction_pair return ObjectPrediction(
> 
> File "D:\Anaconda\lib\site-packages\sahi\prediction.py", line 79, in **init** super().**init**(
> 
> File "D:\Anaconda\lib\site-packages\sahi\annotation.py", line 525, in **init** raise ValueError("Invalid segmentation mask.")
> 
> ValueError: Invalid segmentation mask.
> 
> Have you solved it? How did you solve it?

Unfortunately, I haven't continued researching this issue recently due to being quite busy. If I solve the problem later, I will get back to you. If you solve it before me, feel free to leave a reply. Wish you all the best!😊
